services:
    openball.language.kernel_request_listener:
        class: OpenBall\Bundle\SiteBundle\EventListener\LanguageListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setLocale }